/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddBagForm: typeof import('./src/components/AddBagForm.vue')['default']
    AddRequestForm: typeof import('./src/components/AddRequestForm.vue')['default']
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BDropdown: typeof import('bootstrap-vue-next')['BDropdown']
    BDropdownItem: typeof import('bootstrap-vue-next')['BDropdownItem']
    BloodBagsTable: typeof import('./src/components/BloodBagsTable.vue')['default']
    BNav: typeof import('bootstrap-vue-next')['BNav']
    Dropdown: typeof import('./src/components/Dropdown.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HomeButton: typeof import('./src/components/HomeButton.vue')['default']
    PrimaryButton: typeof import('./src/components/PrimaryButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecondaryButton: typeof import('./src/components/SecondaryButton.vue')['default']
    SolicitationsTable: typeof import('./src/components/SolicitationsTable.vue')['default']
  }
}
